[workspace]
members = ["kernel", "loader", "modules/*", "libs/*", "libs/module/macros"]

[profile.dev]
opt-level = 1

[profile.release]
lto = true
debug = false
strip = true

[workspace.dependencies]
log = { version = "0.4", features = ["release_max_level_trace"] }
